repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12  # Use the latest stable version
    hooks:
      - id: ruff
        name: ruff
        entry: uv
        args: ["run", "ruff", "check", ".", "--fix"]
        language: system
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12  # Use the latest stable version
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv
        args: ["run", "ruff", "format", "."]
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c 'cd app && pnpm run format'
        language: system
        files: ^app/.*\.(js|jsx)$
        pass_filenames: false

      - id: biome-lint
        name: biome-lint
        entry: bash -c 'pnpm run lint:fix'
        language: system
        files: ^app/.*\.(js|jsx)$
        pass_filenames: false
