services:
  backend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./server:/home/legacy-use-mgmt/server
      - ./pyproject.toml:/home/legacy-use-mgmt/pyproject.toml
      - ./uv.lock:/home/legacy-use-mgmt/uv.lock

  frontend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./app:/home/legacy-use-mgmt/app
      - ./package.json:/home/legacy-use-mgmt/package.json
      - ./package-lock.json:/home/legacy-use-mgmt/package-lock.json
      - ./vite.config.js:/home/legacy-use-mgmt/vite.config.js
      - ./index.html:/home/legacy-use-mgmt/index.html
      - ./public:/home/legacy-use-mgmt/public
      - ./tsconfig.json:/home/legacy-use-mgmt/tsconfig.json
      - ./biome.json:/home/legacy-use-mgmt/biome.json
