services:
  postgres:
    image: postgres:17-alpine
    container_name: legacy-use-postgres
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: legacy_use
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  hatchet-lite:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-lite:latest
    ports:
      - "8888:8888"
      - "7077:7077"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/legacy_use?sslmode=disable"
      SERVER_AUTH_COOKIE_DOMAIN: localhost
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_GRPC_BROADCAST_ADDRESS: host.docker.internal:7077
      SERVER_GRPC_PORT: "7077"
      SERVER_URL: http://hatchet-lite:8888
      SERVER_AUTH_SET_EMAIL_VERIFIED: "t"
      SERVER_DEFAULT_ENGINE_VERSION: "V1"
      SERVER_INTERNAL_CLIENT_INTERNAL_GRPC_BROADCAST_ADDRESS: hatchet-lite:7077      
    volumes:
      - "hatchet_lite_config:/config"


  api:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-backend/Dockerfile
    container_name: legacy-use-api
    user: root
    environment:
      - CONTAINER_TYPE=api
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/legacy_use
      - LEGACY_USE_DEBUG=0
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN:-}
      - HATCHET_CLIENT_TLS_STRATEGY=none
      - HATCHET_CLIENT_HOST=hatchet-lite
      - HATCHET_CLIENT_PORT=7077
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
      hatchet-lite:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-backend/Dockerfile
    container_name: legacy-use-worker
    user: root
    environment:
      - CONTAINER_TYPE=worker
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/legacy_use
      - LEGACY_USE_DEBUG=0
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN:-}
      - HATCHET_CLIENT_TLS_STRATEGY=none
      - HATCHET_CLIENT_HOST=hatchet-lite
      - HATCHET_CLIENT_PORT=7077
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      hatchet-lite:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-frontend/Dockerfile
    container_name: legacy-use-frontend
    environment:
      - LEGACY_USE_DEBUG=0
      - VITE_PROXY_TARGET=api
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
  hatchet_lite_config:


