services:
  backend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./server:/home/legacy-use-mgmt/server
      - ./pyproject.toml:/home/legacy-use-mgmt/pyproject.toml
      - ./uv.lock:/home/legacy-use-mgmt/uv.lock

  frontend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - .:/web/
