services:
  backend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./server:/home/legacy-use-mgmt/server
      - ./pyproject.toml:/home/legacy-use-mgmt/pyproject.toml
      - ./uv.lock:/home/legacy-use-mgmt/uv.lock

  frontend:
    environment:
      - LEGACY_USE_DEBUG=1
    volumes:
      - ./app:/web/app
      - ./package.json:/web/package.json
      - ./pnpm-lock.yaml:/web/pnpm-lock.yaml
      - ./vite.config.js:/web/vite.config.js
      - ./index.html:/web/index.html
      - ./public:/web/public
      - ./tsconfig.json:/web/tsconfig.json
      - ./biome.json:/web/biome.json
