services:
  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: legacy-use-postgres
    environment:
      POSTGRES_DB: legacy_use
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # Hatchet Lite - uses existing PostgreSQL
  hatchet:
    image: ghcr.io/hatchet-dev/hatchet/hatchet-lite:latest
    ports:
      - "8080:8080"  # Hatchet UI
      - "7077:7070"  # GRPC
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/legacy_use"
      SERVER_GRPC_BIND_ADDRESS: "0.0.0.0"
      SERVER_GRPC_INSECURE: "t"
      SERVER_AUTH_COOKIE_INSECURE: "t"
      SERVER_AUTH_COOKIE_DOMAIN: ".local.legacy-use.com"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # API Service (formerly backend)
  api:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-backend/Dockerfile
    container_name: legacy-use-api
    user: root
    environment:
      - CONTAINER_TYPE=api
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/legacy_use
      - LEGACY_USE_DEBUG=0
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN:-}
      - HATCHET_CLIENT_TLS_STRATEGY=none
      - HATCHET_CLIENT_HOST=hatchet
      - HATCHET_CLIENT_PORT=7070
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
      hatchet:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  # Worker Service
  worker:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-backend/Dockerfile
    container_name: legacy-use-worker
    user: root
    environment:
      - CONTAINER_TYPE=worker
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/legacy_use
      - LEGACY_USE_DEBUG=0
      - HATCHET_CLIENT_TOKEN=${HATCHET_CLIENT_TOKEN:-}
      - HATCHET_CLIENT_TLS_STRATEGY=none
      - HATCHET_CLIENT_HOST=hatchet
      - HATCHET_CLIENT_PORT=7070
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      postgres:
        condition: service_healthy
      hatchet:
        condition: service_started
    restart: unless-stopped
    env_file:
      - .env

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: infra/docker/legacy-use-frontend/Dockerfile
    container_name: legacy-use-frontend
    environment:
      - LEGACY_USE_DEBUG=0
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
