"""add_user_management_tables

Revision ID: 8e296d962351
Revises: f705ed66700e
Create Date: 2025-08-03 22:01:03.228230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from server.migrations.tenant import for_each_tenant_schema


# revision identifiers, used by Alembic.
revision: str = '8e296d962351'
down_revision: Union[str, None] = 'f705ed66700e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


@for_each_tenant_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=True),
        sa.Column('auth_provider_user_id', sa.String(length=255), nullable=True),
        sa.Column('auth_provider', sa.String(length=50), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='shared',
    )
    op.create_index(
        op.f('ix_shared_users_email'), 'users', ['email'], unique=True, schema='shared'
    )
    op.create_table(
        'user_tenants',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['shared.tenants.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['shared.users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='shared',
    )
    op.create_index(
        'ix_user_tenant_tenant_id',
        'user_tenants',
        ['tenant_id'],
        unique=False,
        schema='shared',
    )
    op.create_index(
        'ix_user_tenant_unique',
        'user_tenants',
        ['user_id', 'tenant_id'],
        unique=True,
        schema='shared',
    )
    op.create_index(
        'ix_user_tenant_user_id',
        'user_tenants',
        ['user_id'],
        unique=False,
        schema='shared',
    )
    op.drop_index(
        op.f('ix_tenant_job_messages_job_id'),
        table_name='job_messages',
        schema='tenant_default',
    )
    op.create_index(
        op.f('ix_tenant_default_job_messages_job_id'),
        'job_messages',
        ['job_id'],
        unique=False,
        schema='tenant_default',
    )
    op.create_index(
        op.f('ix_tenant_default_settings_key'),
        'settings',
        ['key'],
        unique=False,
        schema='tenant_default',
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_tenant_default_settings_key'),
        table_name='settings',
        schema='tenant_default',
    )
    op.drop_index(
        op.f('ix_tenant_default_job_messages_job_id'),
        table_name='job_messages',
        schema='tenant_default',
    )
    op.create_index(
        op.f('ix_tenant_job_messages_job_id'),
        'job_messages',
        ['job_id'],
        unique=False,
        schema='tenant_default',
    )
    op.drop_index('ix_user_tenant_user_id', table_name='user_tenants', schema='shared')
    op.drop_index('ix_user_tenant_unique', table_name='user_tenants', schema='shared')
    op.drop_index(
        'ix_user_tenant_tenant_id', table_name='user_tenants', schema='shared'
    )
    op.drop_table('user_tenants', schema='shared')
    op.drop_index(op.f('ix_shared_users_email'), table_name='users', schema='shared')
    op.drop_table('users', schema='shared')
    # ### end Alembic commands ###
